version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mysql
    env_file:
      - .env.docker
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 111
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mongodb_data:
  mysql_data: